function []=RATInstructions(design)

fontcolor=design.grey;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'Welcome to the Remote Associations Game.', ...
    'This is a word game.', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window); 
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'On each trial, you will be presented with three words in the middle of the screen.', ...
    'The question is: what word pairs with each of the presented words?', ...
    'There is a correct solution to each question', ...
    'Your task is to find the right solution.', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window); 
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'First, read the presented three words carefully.', ...
    'Then, try to generate a fourth word, which combines with each of the three words', ...
    'and would result in word pairs that make up a common compound word or phrase.', ...
    'Once you come up with the fourth word, hold down the space bar while you say that word outloud.', ...
    'The microphone icon means that we are recording your voice.', ...
        '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'You have a total of 30 seconds to come up with the solution,', ...
    'and there are 30 trials in total.', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;


DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'After you are done with the solution to the question,', ...
    'we will ask you to report if you felt a sense of insight ', ...
    'during the solution of the question. ', ...
    '(Press a key to continue reading the instructions.)'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;

DrawFormattedText(design.window, sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s', ...
    'A feeling of insight is a kind of "Aha!" characterized by suddenness and obviousness.', ...
    'You may not be sure how you came up with the answer, but are relatively confident that it', ...
    'is correct without having to mentally check it. It is as though the answer came into mind', ...
    'all at once—when you first thought of the word, you simply knew it was the answer.', ... 
    'This feeling does not have to be overwhelming, but should resemble what was just described.', ...
    '', ...
    'We will ask you report how much "insight" you felt during the solution of each question', ...
    'on a scale of 1 to 6.', ...
    '1 being experiencing no insight, 6 being experiencing complete insight.', ...
    'Now press a key to practice the rules.'), 'center', 'center',fontcolor,[100],[],[],[2]);
Screen('Flip',design.window);
KbStrokeWait;